# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with: 
        persist-credentials: false 
        fetch-depth: 0
    - uses: actions/setup-java@v3     
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: 'maven'        
    - name: Remove snapshot suffix to version
      run: |
        POMPATH=myguestcare-commons
        OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BUMP_MODE="none"
        VERSION="${OLD_VERSION%-SNAPSHOT}"
        mvn -q versions:set -DnewVersion="${VERSION}" --file $POMPATH/pom.xml
        echo ::set-output name=jar_version::${VERSION}
        echo 'you can now generate package and deploy it'
    
    - name: Bump version
      run: |
        POMPATH=myguestcare-commons
        OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BUMP_MODE="none"
        old="$OLD_VERSION"
        parts=( ${old//./ } )
        bv=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.${bv}-SNAPSHOT"
        echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
        mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
        echo ::set-output name=jar_version::${NEW_VERSION}

    - name: Generate Githup App Token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key:  ${{ secrets.APP_PRIVATE_KEY }}    
    
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
       github_token: ${{ steps.generate_token.outputs.token }}

    # - name: Aggiorna file
    #   run: |
    #     touch file.txt
    #     git add file.txt
    #     git commit -m "Aggiorna file.txt"
    #     git push origin main
     

    # - name: Build with Maven
    #   working-directory: ./myguestcare-commons
    #   run: mvn -B package --file pom.xml

    # - name: Publish to GitHub Packages Apache Maven
    #   working-directory: ./myguestcare-commons
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    
    
