# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3     
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: 'maven'        
    - name: Bump version
      run: |
        POMPATH=myguestcare-commons
        OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BUMP_MODE="none"
        old="$OLD_VERSION"
        parts=( ${old//./ } )
        bv=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
        echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
        mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
        echo ::set-output name=jar_version::${NEW_VERSION}
     
    - name: Generate Githup App Token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key:  ${{ secrets.APP_PRIVATE_KEY }}    
    
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
       github_token: ${{ steps.generate_token.outputs.token }}

    # - name: Build with Maven
    #   working-directory: ./myguestcare-commons
    #   run: mvn -B package --file pom.xml

    # - name: Publish to GitHub Packages Apache Maven
    #   working-directory: ./myguestcare-commons
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    
    
